### ISSUE TITLE
Could not find valid optimal solution

### ISSUE THREAD

**Issue by caomuqing** [AIS-Bonn/TopiCo#2]
Hi,

Thanks for this wonderful package. It is very useful. 
I have encountered some issues when using the Matlab program: Very often I encounter the error that no valid optimal solution can be found, and it is usually accompanied by a warning:
 ```
Warning: V_wayp to close to V_min to prevent future violation of constraints with A_wayp and J_max (when constraints stay the same)!
Debug: Generating trajectory for waypoint 1!
Debug: Ax[1] Correcting feasibility!
Debug: Ax[1] Generating optimal solutions!
Error: Could not find valid optimal solution!
Error: This usually can NOT happen. Using idle trajectory to prevent segfault!
 ```
I have pre-processed the inputs to make sure that final velocity are not too negative/positive and final acceleration not too positive/negative at the same time, so that the cases that velocity has to exceed the bound for the acceleration to reach its final value should not occur. In short, I think the inputs should be solvable but the warning and the error still occur.

Instead of asking for a fix, in fact I am more interested in the reasons for the failure to solve: is it because of the numerical problem when the inputs are near the bound, or it is because the optimal trajectory template for these cases is not included in the predefined templates? Or any other reasons that I could not think of. It would be extremely helpful if you could shed some light on the problem.

Thank you!

Best Regards,
mq

**Comment by MariusBeul** [comment]
Hi caomuqing,

thanks for the credit! I never experienced numerical issues near the bounds and I am almost certain that I dind't miss any templates. Of course I can be wrong here, but I fuzz-tested with over 100000000 trajectories...

In the current version, there is a known bug that sometimes can prevent you from finding a trajectory: All templates are solved for a general asymmetric jerk (and also asymmetric velocity and acceleration constraints). I found that for some cases, the analytic solution restricts the inputs to be symmetric. For example it devides by (J_max+J_min), rendering the result NaN. I am in the process of implementing a distinction of cases and providing analytical solutions for symmetric jerk limits but this will take some time. These solutions will also be faster to compute since one can simplify some symbolic expressions with J_max = -J_min. There is a bad workaround in line 54 in synchronize_trajectory.m that makes all input asymmetric, but introduces errors and does not always work.

Can you please check if asymmetric inputs solve the issue in your case?

**Comment by caomuqing** [comment]
Hi MariusBeul,

Thank you for your response! I have modified the jerk inputs and the bounds to be asymmetric, however the error messages are still the same. I have uploaded a set of matlab parameters for you to test:
https://www.dropbox.com/s/ak45xggorb0ocok/error_no_opt_soln.mat?dl=0
You should be able to repeat the issue by importing the parameters and running
```
[J_setp_struct,solution_out,T_waypoints,P,V,A,J,t] = topico(x_s_new,Waypoints,V_max,V_min,A_max,A_min,J_max,J_min,A_global,b_sync_V,b_sync_A,b_sync_J,b_sync_W,b_rotate,b_hard_V_lim,b_catch_up,direction,ts_rollout);
```
Thank you!

**Comment by MariusBeul** [comment]
Hi cao muqing,
I was able to reproduce the issue and was able to fix it!
Indeed the problem was the waypoint velocity beeing close to V_max. Since the waypoint acceleration was also positive, this configuration provokes a constraint violation in the future. The algorithm mistakenly discarded all trajectories leading into such a configuration. It now allow these trajectories, but a warning is issued.
Thanks again for pointing this out!

**Comment by caomuqing** [comment]
Hi Marius,

Thank you for your fix and the explanation! I tested the update and it is able to solve the trajectory!
Unfortunately, I still met a very similar problem (but probably with a different cause) which results in no valid solution. I have tested different asymmetric bounds but to no avail.
I have uploaded a new set of matlab parameters for you to test:
https://www.dropbox.com/s/rqtvgqwjjg9ssw0/error2.mat?dl=0
Similarly, you should be able to repeat the issue by running
```
[J_setp_struct,solution_out,T_waypoints,P,V,A,J,t] = topico(x_s_new,Waypoints,V_max,V_min,A_max,A_min,J_max,J_min,A_global,b_sync_V,b_sync_A,b_sync_J,b_sync_W,b_rotate,b_hard_V_lim,b_catch_up,direction,ts_rollout);
```
Once again thank you for your time and this is really helpful!

**Comment by MariusBeul** [comment]
Hi cao muqing,
I pushed a fix that addresses your issue. The problem was that your waypoint causes a constraint violation in the future (which is allowed), but that simultaneously the trajectory was very short (1.4s). This provoked not only the waypoint to be in the future-violation-state, but already the state after the second jerk segment. Therefore, the trajectory following the J_max - J_min - J_max pattern was rejected. The fix now allows the state after the second jerk segment to be in this state IF the waypoint is forced to violate constraints in the future.

Thanks again for helping to make the package better!

**Comment by caomuqing** [comment]
Hi Marius,

Thank you for solving my problem, you are amazing!
